version: '3.8'

services:
  api:
    build:
      context: ./Net/GlobalSolution
    ports:
      - "5149:5149"
    depends_on:
      - oracle
    environment:
      - ConnectionStrings__DefaultConnection=User Id=system;Password=oracle;Data Source=//oracle:1521/XEPDB1;
    networks:
      - backend

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
    networks:
      - backend

networks:
  backend:
    driver: bridge
